#!/bin/sh

pkg=pup-volume-monitor
ver="$(grep -m1 AC_INIT configure.ac | cut -f 3 -d '[' | cut -f 1 -d ']')"
ver=$(echo $ver)

#==============================

dir=${pkg}-${ver}

mkdir -p ../$dir

cp -rf $PWD/* ../$dir

(
	cd ../$dir
	./autogen.sh
	rm -rf autom4te.cache .tx
	#rm -rf m4
	rm -f zrelease
)

cd ..

tar -Jcf ${dir}.tar.xz $dir

