#!/bin/sh

[ -f /etc/DISTRO_SPECS ] && PUPPY_LINUX=yes

if [ "$PUPPY_LINUX" = "yes" ] ; then
	[ "`whoami`" != "root" ] && exec sudo -A ${0} ${@}
fi

#Check whether the daemon is already running
if pup-volume-monitor-admin --list-all &> /dev/null; then
	echo "ERROR: pup-volume-monitor daemon is already running."
	exit 2
fi

case $1 in -d|-debug)
		export G_MESSAGES_DEBUG=all
		while true; do
			pup-volume-monitor 2>&1 > /tmp/pup-volume-monitor.log
			sleep 5
		done 
		;;
esac

if [ "$PUPPY_LINUX" = "yes" ] ; then
	pup-volume-monitor &
	if ! grep -q root /etc/inittab ; then
		sleep 4
		if [ -e /tmp/pup_volume_monitor_socket ] ; then
			chmod 777 /tmp/pup_volume_monitor_socket 
		fi
	fi
else
	exec pup-volume-monitor
fi

### END ###
